### ISSUE TITLE
Cant change camera movement speed

### ISSUE THREAD

**Issue by AzikDeveloper** [VictorGordan/opengl-tutorials#1]
hey . I can not change the movement speed of camera. its very fast so I lose the pyramid if I move around it

**Comment by VictorGordan** [comment]
That's probably because you have VSync turned off, so the program checks if you are pressing the movement buttons thousands of time a second and so the movement that is applied will be thousands of times per second. Either turn of VSync, or put the camera inputs inside an if statement that is only true every X seconds. I would recommend X to be smth like a 60th of a second.

I talk about this in tutorial 16 and also show some code for this there. Good luck! :)

**Comment by VictorGordan** [comment]
Also, you can obviously change the speed of the camera by changing the "speed" variable in "Camera.h". Just keep in mind it will differ with the frequency at which you handle the inputs.
